resources:
  - name: pipelinesBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artiIntegration
      buildName: pipelinesTestBench
      buildNumber: 1
  - name: PropBagTest
    type: PropertyBag
    configuration:
      name: 'notset'
      id: 'boj-notset'
  - name: myFirstRepo2
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: derekTestIntegration
      # Repository path, including org name/repo name
      path: derekscp/jfrog-pipelines-simple-example
      branches:
        # Specifies which branches will trigger dependent steps
        include: master
      
pipelines:
   - name: test_pipe2    
     steps:
      - name: firstStep
        type: Bash
        configuration:
          inputResources:
            - name: myFirstRepo2
          outputResources:
            - name:  PropBagTest
        execution:
          onExecute:
            - echo $current_runid
            # Writes current run number to pipeline state
            - add_pipeline_variables prev_runid=$run_id
            - export JFROG_CLI_BUILD_NUMBER=${run_number}
            - export JFROG_CLI_BUILD_NAME=lab_ami_centos_7_hardened
            # Uses an utility function to update the output resource with the commitSha that triggered this run
            # Dependent pipelines can be configured to trigger when this resource is updated
            # Utility functions documentation: https://www.jfrog.com/confluence/display/JFROG/Pipelines+Utility+Functions
            - write_output  PropBagTest name="someName" id="newId"
            
      - name: checkChange
        type: Bash
        configuration:
          inputResources:
           - name: PropBagTest
        execution:
          onExecute:
           - printenv res_PropBagTest_name
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: firstStep
          outputResources:
            - name: pipelinesBuildInfo
        execution:
          onStart:
            - env
          onComplete:
            - env
